version: '2'
services:
  mysqldata:
    image: busybox
    container_name: mysqldata
    volumes:
     - /var/lib/mysql
  mysql:
    build: ./mysql
    container_name: mysql
    stdin_open: true
    tty: false
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes_from:
      - mysqldata
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/docker
  app:
    build: ./app
    container_name: app
    stdin_open: true
    tty: false
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./apache:/etc/apache2/sites-enabled/
    depends_on:
      - mysql
